version: "3.8"

services:
  api: # <-- ADDED: The NestJS Application
    build:
      context: ./focusbear-practice
      dockerfile: Dockerfile
    container_name: focusbear-api
    ports:
      - "3000:3000"
    environment:
      # Notice how the host is 'db' (the name of the Postgres service below)
      DATABASE_URL: postgres://admin:mysecurepassword@db:5432/focusbear_dev
    volumes:
      - ./focusbear-practice:/usr/src/app # Syncs your local code for hot-reloading
      # - /usr/src/app/node_modules # Prevents local node_modules from overwriting the container's
    depends_on:
      - db # Ensures the database starts before the API
      - redis

  db:
    image: postgres:16 # Use a specific version to match production
    container_name: focusbear-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB: focusbear_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # This is where the magic (persistence) happens
  redis:
    image: redis:7-alpine
    container_name: focusbear-redis
    ports:
      - "6380:6379" # Exposes Redis to your host machine for debugging
    volumes:
      - redis_data:/data
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    # Vite needs the --host flag to be accessible outside the Docker container!
    command: sh -c "npm install && npm run dev -- --host"
volumes:
  pgdata: # Declares the named volume
  redis_data:
